INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (1, 'Sin datos', 'Arroz a la cubana', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (2, 'Sin datos', 'Arroz con verduras y pollo', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (3, 'Sin datos', 'Chipirones + humus con crudites', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (4, 'Sin datos', 'Crema + mini tosta', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (5, 'Sin datos', 'Emperador + espárragos blancos', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (6, 'Sin datos', 'Ensalada de pasta', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (7, 'Sin datos', 'Fajitas vegetales', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (8, 'Sin datos', 'Filetes de pavo + tomate', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (9, 'Sin datos', 'Garbanzos con chorizo', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (10, 'Sin datos', 'Gazpacho + revuelto a lo Luis', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (11, 'Sin datos', 'Gazpacho/salmorejo + restos', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (12, 'Sin datos', 'Hamburguesas y champis', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (13, 'Sin datos', 'Libuna al horno con papas', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (14, 'Sin datos', 'Pescado + calabacín plancha', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (15, 'Sin datos', 'Pimientos rellenos de verduras y atún', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (16, 'Sin datos', 'Pollo al horno + brocoli', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (17, 'Sin datos', 'Revuelto a lo Luis', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (18, 'Sin datos', 'Rollos de salmón y espárragos', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (19, 'Sin datos', 'Wok de verduras y pollo', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (20, 'Sin datos', 'Wrap carne picada', 'Sin datos');
INSERT INTO `wmp_dish` (`dish_id`,`ingredients`,`name`,`recipe`) VALUES (21, 'Sin datos', 'Wraps vegetales', 'Sin datos');
